-- Create tours table
create table public.tours (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  duration text not null,
  image text not null,
  price text not null,
  group_size text default 'Small Group',
  slug text not null unique,
  inclusions text[] default array['Meals', 'Stay', 'Guide']::text[],
  category text not null -- e.g. 'featured', 'heritage', 'nature'
);

-- Enable RLS for tours
alter table public.tours enable row level security;

-- Create policy to allow read access for all
create policy "Allow public read access"
  on public.tours for select
  using (true);

-- Create destinations table
create table public.destinations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  location text not null,
  image text not null,
  price text not null,
  rating numeric default 5.0,
  slug text not null unique,
  description text,
  category text not null -- e.g. 'featured', 'first-time', 'adventure'
);

-- Enable RLS for destinations
alter table public.destinations enable row level security;

-- Create policy to allow read access for all
create policy "Allow public read access"
  on public.destinations for select
  using (true);

-- Create profiles table (optional, for specific user data)
create table public.profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  constraint username_length check (char_length(username) >= 3)
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Function to handle new user signup
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;

-- Trigger for new user signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
